# Moved to task-1 because done with this YAML file however 
# when you want to run this it must be in the .github/workflows
# otherwise pipeline will not work

name: Linting a Dockerfile 
on: [push]

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code 
              uses: actions/checkout@v4

            - name: Lint Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: ./cicd/task-1/Dockerfile