name: Linting a Dockerfile 
on: [push]

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code 
              uses: actions/checkout@v4

            - name: Lint Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: ./cicd/task-1/Dockerfile